config/routes.rb
DiscGolfTracker::Application.routes.draw do
  
  devise_for :users

  root(:to => 'home#index')
  
  resources(:discs) do
    member do
      post 'remove'
    end
  end
    
  match ':action' => 'static_pages#:action'

end

app/models/disc.rb
class Disc < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible(:disc_id, :userid, :name, :style, :brand, :plastic, :color, :stability, :weight, :level)

  validates(:name, presence: true)
  validates(:style, presence: true)
  validates(:brand,presence: true)
  validates(:plastic, presence: true)
  validates(:color, presence: true)
  validates(:stability, presence: false)
  validates(:weight, presence: false)
  validates(:level, presence: false)

  belongs_to(:disc_color, :foreign_key => "color")
  belongs_to(:disc_brand, :foreign_key => "brand")
  belongs_to(:disc_style, :foreign_key => "style")
  belongs_to(:disc_name, :foreign_key => "name")
  belongs_to(:disc_level,:foreign_key => "level")
  belongs_to(:disc_plastic, :foreign_key => "plastic")
  belongs_to(:disc_stability, :foreign_key => "stability")
  belongs_to(:disc_weight, :foreign_key => "weight")
  belongs_to(:user, :foreign_key => "id")
end

app/controllers/discs_controller.rb
class DiscsController < ApplicationController
  before_filter(:authenticate_user!)

  # GET /discs
  # GET /discs.json
  def index
    # @output = "Current Playerid: #{current_user.id}"

    @discs = Disc.where("user_id = #{current_user.id}")

    respond_to do |format|
      if @discs.size == 0
        format.html { render :action => "show" }
        format.json { render json: @discs }
      else
        format.html
      end
    end
  end

  # GET /discs/1
  # GET /discs/1.json
  def show
    respond_to do |format|

      format.html # index.html.erb
      format.json { render json: @disc }
    end
  end

  # GET /discs/new
  # GET /discs/new.json
  def new
    @disc = Disc.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @disc }
    end
  end

  # GET /discs/1/edit
  def edit
    @disc = Disc.find(params[:id])
  end

  # POST /discs
  # POST /discs.json
  def create
    # @disc = Disc.new(params[:disc])
    params[:disc][:disc_id] = SecureRandom.hex(10)
    @disc = Disc.create(params[:disc])

    respond_to do |format|
      if @disc.save
       # format.html { redirect_to @disc, notice: 'Disc was successfully created.' }
        format.html { redirect_to :action => "index"}
        format.json { render json: @disc, status: :created, location: @disc }
      else

        format.html { render action: "new" }
        format.json { render json: @disc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /discs/1
  # PUT /discs/1.json
  def update
    @disc = Disc.find(params[:id])

    respond_to do |format|
      if @disc.update_attributes(params[:disc])
        #format.html { redirect_to @disc, notice: 'Disc was successfully updated.' }
        format.html { redirect_to :action => "index"}
        format.json { head :no_content }
      else
        format.html { render action: "index" }
        format.json { render json: @disc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discs/1
  # DELETE /discs/1.json
  def destroy
    @disc = Disc.find(params[:id])
    @disc.destroy

    respond_to do |format|
      format.html { redirect_to discs_url }
      format.json { head :no_content }
    end
  end

  # REMOVE /discs/1
  def remove
    @disc = Disc.find(params[:id])
    @disc.update_attributes(:user_id => 0)

    respond_to do |format|
        format.html {redirect_to :action => "index"}
    end
  end
end

app/helpers/discs_helper.rb
module DiscsHelper
end

app/views/discs/_form.html.erb
<%= link_to('Log out', destroy_user_session_url,
                  :method => :delete,
                  :confirm => "Are you sure you want to log out?") %> | 
<%= link_to 'Add Disc', new_disc_path %> | 
<%= link_to 'Back', discs_path %>

<br/><br/>
<%= form_for(@disc) do |f| %>
  <% if @disc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@disc.errors.count, "error") %> prohibited this disc from being saved:</h2>

      <ul>
        <% @disc.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset id="add_edit">
    <%= f.hidden_field(:playerid, :value => current_user.id) %>
    <ul id="double">
      <li>
        <label for="name">Name:</label>

        <%= collection_select(:disc, :name, DiscName.order('name ASC').all, :id, :name) %>
      </li>

      <li>
        <label for="style">Style:</label>
        <%= collection_select(:disc, :style, DiscStyle.order('style ASC').all, :id, :style) %>
     </li>

      <li>
        <label for="brand">Brand:</label>
        <%= collection_select(:disc, :brand, DiscBrand.order('brand ASC').all, :id, :brand) %>
      </li>

      <li>
        <label for="plastic">Plastic:</label>
        <%= collection_select(:disc, :plastic, DiscPlastic.order('plastic ASC').all, :id, :plastic) %>
      </li>

      <li>
        <label for="color">Color:</label>
        <%= collection_select(:disc, :color, DiscColor.order('color ASC').all, :id, :color) %>
      </li>

      <li>
        <label for="stability">Stability:</label>
        <%= collection_select(:disc, :stability, DiscStability.order('stability ASC').all, :id, :stability) %>
      </li>

      <li>
        <label for="weight">Weight:</label>
        <%= collection_select(:disc, :weight, DiscWeight.order('weight ASC').all, :id, :weight) %>
      </li>

      <li>
        <label for="level">Level:</label>
         <%= collection_select(:disc, :level, DiscLevel.order('level ASC').all, :id, :level) %>
      </li>
    </ul>

  </fieldset>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</br>
<div id="output">
  <%= @output %>
</div>
<br/>
<br/>
<%= link_to('Log out', destroy_user_session_url,
                  :method => :delete,
                  :confirm => "Are you sure you want to log out?") %>
| <%= link_to 'Add Disc', new_disc_path %> | <%= link_to 'Back', discs_path %>

app/views/discs/index.html.erb
<h2>My Tracker</h2>

<%= link_to('Log out', destroy_user_session_url,
                  :method => :delete,
                  :confirm => "Are you sure you want to log out?",
                  :class => 'button') %>
<%= link_to 'Add Disc', new_disc_path, :class => 'button' %> 
<%= link_to 'Back', discs_path, :class => 'button' %>

<br/><br/>
<table border="2" width="100%">
  <tr>
    <th>Edit</th>
    <th>Remove</th>
    <th>DiscID</th>
    <th>Name</th>
    <th>Style</th>
    <th>Brand</th>
    <th>Plastic</th>
    <th>Color</th>
    <th>Stability</th>
    <th>Weight</th>
    <th>Level</th>
  </tr>

<% @discs.each do |disc| %>

  <tr class = "<%= cycle("even", "odd") %>">
    <!--<td><%# link_to 'Show', disc %></td> -->
    <td><%= link_to 'Edit', edit_disc_path(disc) %></td>
    <td><%= link_to 'Remove', remove_disc_path(disc), method: :post, data: { confirm: 'Are you sure?' } %></td>
    <td><%= disc.disc_id %>
    <td><%= disc.disc_name.name %>
    <td><%= disc.disc_color.color %>
    <td><%= disc.disc_brand.brand %>
    <td><%= disc.disc_plastic.plastic%>
    <td><%= disc.disc_color.color %>
    <td><%= disc.disc_stability.stability%>
    <td><%= disc.disc_weight.weight%>
    <td><%= disc.disc_level.level%>
  </tr>
<% end %>
</table>
</br>
<%= link_to('Log out', destroy_user_session_url,
                  :method => :delete,
                  :confirm => "Are you sure you want to log out?",
                  :class => 'button') %>
<%= link_to 'Add Disc', new_disc_path, :class => 'button' %> 
<%= link_to 'Back', discs_path, :class => 'button' %>

app/views/discs/new.html.erb
<h2>Add Disc</h2>
<%= render 'form' %>

app/views/discs/show.html.erb
<h2>My Tracker</h2>

<%= link_to('Log out', destroy_user_session_url,
                  :method => :delete,
                  :confirm => "Are you sure you want to log out?",
                  :class => 'button') %>
<%= link_to 'Add Disc', new_disc_path, :class => 'button' %> 
<%= link_to 'Back', discs_path, :class => 'button' %>

<br/><br/>
<table border="2" width="100%">
  <tr>
    <th>Edit</th>
    <th>Remove</th>
    <th>DiscID</th>
    <th>Name</th>
    <th>Style</th>
    <th>Brand</th>
    <th>Plastic</th>
    <th>Color</th>
    <th>Stability</th>
    <th>Weight</th>
    <th>Level</th>
  </tr>
  <tr>
  	<td colspan="11" align="center"><h3>You currently have no discs listed.</h3></td>
  </tr>
</table>
</br>
<%= link_to('Log out', destroy_user_session_url,
                  :method => :delete,
                  :confirm => "Are you sure you want to log out?",
                  :class => 'button') %>
<%= link_to 'Add Disc', new_disc_path, :class => 'button' %> 
<%= link_to 'Back', discs_path, :class => 'button' %>