config/routes.rb
DiscGolfTracker::Application.routes.draw do
  
  devise_for :users

  root(:to => 'home#index')
  
  resources(:discs) do
    member do
      post 'remove'
    end
  end
    
  match ':action' => 'static_pages#:action'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_chromeframe.html.erb
<%# Prompt IE 6 users to install Chrome Frame. Remove this if you support IE 6. %>
<%# chromium.org/developers/how-tos/chrome-frame-getting-started %>
<!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->

app/views/application/_footer.html.erb
<footer id="footer">
  <small class="copyright">
    Disc Golf Tracker, Copyright &copy; <%= Date.today.year %> | <a href="http://fineartamerica.com/art/photographs/trees/all" style="font: 10pt arial; text-decoration: underline;">Trees photo</a>
  </small>
</footer>

app/views/application/_head.html.erb
<head>
  <meta charset="utf-8">

  <%# Use the .htaccess and remove these lines to avoid edge case issues. %>
  <%# More info: h5bp.com/b/378 %>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title></title>
  <meta name="description" content="">

  <%# Mobile viewport optimized: h5bp.com/viewport %>
  <meta name="viewport" content="width=device-width">

  <%=  render "stylesheets" %>
   
  <%# More ideas for your <head> here: h5bp.com/d/head-Tips %>

  <%# All JavaScript at the bottom, except polyfills %>
  <%= javascript_include_tag "polyfills" %>

  <%= csrf_meta_tag %>
</head>

app/views/application/_header.html.erb
<header id="header">
    
     <h1>DiscGolfTracker</h1>

	<p class="notice"<%= notice %>></p>
	<p class="alert"><%= alert %></p>
	
	<menu>
		<ul id="nav" class="button-group">
          <li><%= link_to 'Home', root_url, :class => "button primary pill"%>
            <!--<ul>
              <li><%# link_to('Log out', destroy_user_session_url,
                  :method => :delete,
                  :confirm => "Are you sure you want to log out?") %></li>
             </ul>
          </li>-->
          <li><%= link_to 'Courses', '/courses', :class => "button pill"%></li>
          <li><%= link_to 'How To Play', '/rules', :class => "button pill"%></li>
          <li><%= link_to 'Account', discs_url, :class => 'button pill'%>
            
          </li>
          <li><%= link_to 'Credits', '/credits', :class => "button pill"%></li>
        </ul>
	</menu>
</header>

app/views/application/_rules.html.erb
<menu>
   <%= link_to 'Disc Styles', '/discstyle' %> |
   <%= link_to 'Throwing', '/throwingstyle' %> | 
   <%= link_to 'Components', '/coursecomponents' %> | 
   <%= link_to 'Scoring', '/scoring' %>
</menu>